name: ONPUNCH Tunnel

on:
  workflow_dispatch:

jobs:
  setup-punch-tunnel:
    runs-on: windows-latest

    steps:
    - name: Check code
      uses: actions/checkout@v3
      
    - name: Echo Test
      run: |
        # 添加你需要执行的命令
        echo "开始设置 ONPUNCH Tunnel..."
        # 例如：安装软件、运行脚本等
