name: ONPUNCH Tunnel

on:
  workflow_dispatch:

jobs:
  setup-punch-tunnel:
    runs-on: windows-latest

    steps:
    - name: Check code
      uses: actions/checkout@v3
      
    - name: Echo Test
      run: |
        # 添加你需要执行的命令
        echo "开始设置 ONPUNCH Tunnel..."
        # 例如：安装软件、运行脚本等
    
    - name: Install
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Sleep -Seconds 5

    - name: Settings
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "p@ssw0rd!" -Force)

    - name: Start
      env:
        PLAYIT_AUTH_KEY: "a0d8368e53b804180071a05c5df7d34f9eaf679f37229f90fdf0a4ff1dc12d21" 
      run: |
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow

    - name: Routine
      run: |
          Start-Sleep -Seconds 11700
